### ISSUE TITLE
Opening connection to BG osumer socket Returned message: Could not open socket at 46725 for BG call. Not osumer running at that port?

### ISSUE THREAD

**Issue by takase1121** [mob41/osumer#10]
### My environment

- My operating system: Windows 8.1

- My Java Version: Java 8 Update 151

### About my issue

Sometimes when I started osumer, the error occurs. It said something about "socket error", seems like it can't connect to the osumer daemon at the background. I double checked that osumer daemon is running at the background. I failed to find any dump information while trying to combine the dump files, so I only got the dump file from the "Unexpected Error" dialog.

### Dump files

[osumer-debugDump-1514508249514.txt](https://github.com/mob41/osumer/files/1592448/osumer-debugDump-1514508249514.txt)

**Comment by a1aw** [comment]
Is the error occurs even though the UI has jumped out when you "clicked on the osumer.exe / Shortcut"?

**Comment by takase1121** [comment]
I am not sure as it didn't happen everytime, but when it happens my computer lags a lot and harddisk activity peaked 100%

**Comment by 0kolya0** [comment]
reinstall osumer(delete **ALL** files osumer in your pc)
C:\Program Files\osumer
and Registry

**Comment by a1aw** [comment]
Will be changed to use RMI.
