### ISSUE TITLE
Big memory usage...

### ISSUE THREAD

**Issue by takase1121** [mob41/osumer#11]
osumer version: 2.0.0-SNAPSHOT -b 3
OS: Windows 8.1
Java: Java 8 Update 151

Since I started using osumer, the memory usage increased. It maxed out at around 250MB. I wonder if this is a problem with my computer, my system, Java or the osumer program? Help will be appreciated. 
![capture](https://user-images.githubusercontent.com/20792268/34427557-7d0e728a-ec7e-11e7-8d1d-2e5b017d378e.JPG)

**Comment by a1aw** [comment]
Yeah, I got this problem also. There might be resource leaking from the program. I am checking right now

**Comment by a1aw** [comment]
handled with java RMI and limited heap space
