### ISSUE TITLE
Negative values in ETA counter

### ISSUE THREAD

**Issue by takase1121** [mob41/osumer#12]
### My environment

- My operating system: Windows8.1

- My Java Version: Java 8 Update 151

### About my issue

Sometimes the ETA counter will display negative value in seconds only. This situation only appears on maps around 10MB in size(because it took me around 40 minutes to download a 10MB file). It did not happen on smaller maps.

(note the red box)
![capture](https://user-images.githubusercontent.com/20792268/34428321-6d69c958-ec86-11e7-80b7-72454b71d326.JPG)

**Comment by a1aw** [comment]
Noted. Btw, is the download still requires >20 min to download in browser?

**Comment by takase1121** [comment]
It takes over 20 minutes to download the map in the browser but to be precise the time used is 20:30.6(mm:ss.s). It took shorter time to download compared with osumer. 

The map is 8.34MB big.

**Comment by takase1121** [comment]
Forgot to said that osumer daemon did not launch at startup. It wasn't disabled either in task manager but it just doesn't launch at startup. I have to launch it manually.

**Comment by a1aw** [comment]
Fixed
