### ISSUE TITLE
Strange numbers in the beatmap preview at the "search beatmaps" tab

### ISSUE THREAD

**Issue by takase1121** [mob41/osumer#13]
Strange numbers appear in the "beatmap preview" window when I use the "Search Beatmap" function. How can I have a star difficulty of -1? I suspect that the program uses the same "Beatmap preview" window when trying to "preview" a beatmap pack, and unable to parse the right data. I suggest that when we are "preview"ing a beatmap pack, the difficulty of all maps should be shown, instead of a single, specific beatmap.

![bug1](https://user-images.githubusercontent.com/20792268/34649930-56bdb2e0-f3f3-11e7-82b8-85d5afdaeced.JPG)

**Comment by a1aw** [comment]
I have implemented the things to decode Star Fields (e.g. CS,AR,StarDiff) something. But I haven't hooked them into it, so it shows -1 for all beatmaps.
I will implement asap when I'm free

Regards,
mob41

**Comment by takase1121** [comment]
Ok thanks!
