### ISSUE TITLE
"Thumb Fetch Error" kept occuring in the "Search Beatmaps" tab

### ISSUE THREAD

**Issue by takase1121** [mob41/osumer#14]
I can't get the thumb of the beatmaps! This keeps occuring even though my Internet connection is well.

![bug2](https://user-images.githubusercontent.com/20792268/34649962-c6e22ba0-f3f3-11e7-8cb1-2dd39ca44b3b.JPG)

**Comment by a1aw** [comment]
"Re-"scrolling would help. This implementation to show the results is going to be deprecated in next build.

**Comment by takase1121** [comment]
Thanks!
