### ISSUE TITLE
Error start osumer

### ISSUE THREAD

**Issue by 0kolya0** [mob41/osumer#16]

**Comment by 0kolya0** [comment]
new dump files under this line -->
[osumer-debugDump-1519410081241.txt](https://github.com/mob41/osumer/files/1752712/osumer-debugDump-1519410081241.txt)

**Comment by a1aw** [comment]
Hi, sorry for a late reply.

I have previously known that you have issues with starting osumer from the background that shows a socket error, and another problem with checking updates.

- Socket error
    - Are you running with high cpu usage? That might be a issue that osumer won't response. Or I will try to increase the timeout in the future.

- Update problem
    - Do you have an internet connection? Or osumer might be blocked by your Windows Firewall or Antivirus from accessing the internet. Please check about it.

**Comment by 0kolya0** [comment]
//Sorry i deleted my post. 
Hi, I solved the problem with an error simply by reinstalling osumer (it was difficult) but there was another problem osumer started but not displayed in the background

**Comment by a1aw** [comment]
Oh, it's good to hear that the problem has been solved. This briefly shows that the installation and uninstallation are pretty messy and difficult for end users. This will be marked.
