### ISSUE TITLE
error [nem style urls]

### ISSUE THREAD

**Issue by Hexality** [mob41/osumer#17]
after the new osu!web update, the osumer can't download any maps directly from the server

**Comment by a1aw** [comment]
This problem will be solved soonly.

**Comment by a1aw** [comment]
A new web-page parser is required for this. So it might take time to fix.

**Comment by a1aw** [comment]
Your problem should be solved **temporarily** in ```2.0.0-snapshot-b4```. Please update your osumer to fix it.
