### ISSUE TITLE
"Could not obtain update info"

### ISSUE THREAD

**Issue by Ferrenom** [mob41/osumer#18]
### My environment

- My operating system: Windows 8.1

- My Java Version: Version 8 Update 161

### About my issue

Every time I opened osumer it keeps saying could not obtain update info even with administration privilages

**Comment by a1aw** [comment]
Please reproduce the problem and post the debug dump by: ```osumer2 > View dumps > Combine dumps and export```. And upload the generated ```.txt``` file to here by dragging/selecting them/paste to the comment.

"Could not obtain update info" problem will produce a dump for its error. This can briefly let me find and solve the problem quickly.

I think it is some kind of networking problem on your computer. I don't get this error on my computer.

Update file is hosted on GitHub, but I don't see the server down previously: https://status.github.com/messages
