### ISSUE TITLE
Can't log in due to (likely) password having non-ASCII characters

### ISSUE THREAD

**Issue by KatouMegumi-osu** [mob41/osumer#19]
### My environment

- My operating system: W10

- My Java Version: 1.7_160

**Comment by a1aw** [comment]
Sorry for a really late reply, cause I am pretty busy these days.

Your problem has been solved in ```2.0.0-SNAPSHOT-b5```. You can either download it from [the releases](https://github.com/mob41/osumer/releases/tag/2.0.0-SNAPSHOT-b4) or wait it to arrive to your existing version.

P.S. For a kindly reminder, you are **not recommended** to use **non-ASCII** characters as your password in any case.
