### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by TheArcaneBrony** [mob41/osumer#20]
Is this project still alive? We havent seen a commit on here in months.

**Comment by a1aw** [comment]
The project isn't dead. The next step of this project is to separate into modules. However, I haven't got time right now to do it.

Did you encounter problems previously? If not, only critical bugs will be processed immediately.

**Comment by TheArcaneBrony** [comment]
Nope, but I noticed the git repo hasnt gotten any pushes in months now so I thought it was dead.

Thanks for taking the time to respond!
