### ISSUE TITLE
The song name with "*" doesn't start downloading

### ISSUE THREAD

**Issue by 0x0000087** [mob41/osumer#21]
### My environment

- My operating system: *OS X 10.12.6*

- My Java Version: *Java JRE 8 Update 5*

### About my issue

As title
Here is a picture show downloading status 
[pic](https://i.imgur.com/hkUUqJK.jpg)
### Dump files

===!===!===!===!-osumer-debugger-dump-!===!===!===!===
Debug information generated on Sun Nov 04 21:38:04 CST 2018 (1541338684458 ms)
osumerDebugger v.unknown(updater)
osumer v.unknown(updater)

O/S Name: Windows XP

Current operation: Error reporting and debug dump
Returned message: Error when downloading

Last operation: (Try&catch try)
Next operation: (Try&catch finally)

Data specified: null

Exception stacktrace: 
java.io.FileNotFoundException: C:\users\p\Temp\371569 Minamotoya feat. Kuroa* - Hana Kagerou.osz (Invalid name)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:236)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:118)
	at com.github.mob41.osums.io.beatmap.OsuDownloader.run(OsuDownloader.java:164)
	at java.lang.Thread.run(Thread.java:745)

===!===!===!===!-dump-end-!===!===!===!===

**Comment by a1aw** [comment]
It seems there is something wrong with the file name auto-correction in the application. This problem is going to be investigated later on. Thanks!

**Comment by a1aw** [comment]
be fixed in b6
