### ISSUE TITLE
Doesn't detect my Opera browser?

### ISSUE THREAD

**Issue by Adim2P** [mob41/osumer#22]
Is this program limited to number of browsers only? For some reason the program can't detect my Opera browser

**Comment by a1aw** [comment]
How is your Opera browser installed, with administrative privilege or not? Is it installed to the Program Files or AppData?

osumer checks the browsers registered in the Windows Registry to detect installed browsers. It should support most browsers that are properly installed and registered in the registry.

**Comment by Adim2P** [comment]
It's installed in the Appdata local programs folder currently installed it
without adminstrator privilages, should I reinstall with administrator
privilages?

**Comment by Adim2P** [comment]
Yeh everything I do doesn't work so the program can't detect my browser and it doesn't work in game, I tried reinstalling Opera on Admin privilages still no avail can't be detected, I wanted to try uninstalling the osumer express but I can't whatsoever since it's saying I need to uninstall it using the external releases but the external releases say the same error so I'm lost at hope I did follow every single instructions but nothing works.

**Comment by Adim2P** [comment]
I installed Firefox to no avail I was able to reinstall osumerExpress still doesn't work  whatsoever in game still redirects to me firefox itself, I had high hopes for this program, I'll probably snoop around and make it work for me. P.S. I did even set osumerExpress as a def program

**Comment by a1aw** [comment]
Seems to be Opera's problem?

https://www.google.com/search?q=Opera+default+browser+not+in+registry&oq=Opera+default+browser+not+in+registry&aqs=chrome..69i57.6103j0j7&sourceid=chrome&ie=UTF-8

https://forums.opera.com/topic/25085/opera-default-browser/34

https://www.reddit.com/r/operabrowser/comments/7po0xr/i_cant_set_opera_as_default_browser_no_matter/

**Comment by a1aw** [comment]
Many people in the internet cannot even set Opera as default browser in their computer. Osumer depends on that default browsers registry keys so I think that won't be a problem on us.

Maybe should I add an option for users to add their custom browsers?

**Comment by 0kolya0** [comment]
Instal Opera for all user Windows

**Comment by 0kolya0** [comment]
> Many people in the internet cannot even set Opera as default browser in their computer. Osumer depends on that default browsers registry keys so I think that won't be a problem on us.
> 
> Maybe should I add an option for users to add their custom browsers?

Hi, make a download error in the browser when the download fails

**Comment by a1aw** [comment]
> I installed Firefox to no avail I was able to reinstall osumerExpress still doesn't work whatsoever in game still redirects to me firefox itself, I had high hopes for this program, I'll probably snoop around and make it work for me. P.S. I did even set osumerExpress as a def program

I am sorry for that. The application currently still doesn't have a proper way to uninstall itself conveniently. You can uninstall the application with the following instructions:

1. Download ```osumer.exe``` again or copy osumer.exe from ```C:\Program Files\osumer``` to Desktop.
2. Ensure "osumer" is not running at background. It can be done checking the tray icons, clicking on the osumer tray icon. ```osumer2 > Exit > Yes (if any)```
3. Start the ```osumer.exe``` in Desktop with administrative privileges
4. Go to ```Preferences```
5. ```osumerExpress``` and press ```Uninstall osumerExpress```

**Comment by a1aw** [comment]
>Hi, make a download error in the browser when the download fails

@0kolya0 Sorry... what do you mean? 😕

**Comment by 0kolya0** [comment]
> > Hi, make a download error in the browser when the download fails
> 
> @0kolya0 Sorry... what do you mean? 😕

if osumer download error auto open beatmaps on browsers

**Comment by a1aw** [comment]
> Instal Opera for all user Windows

@Adim2P Yeah, try this. Start the Opera installer with administrative privileges. And click ```Install for All Users``` in the installer wizard. This may help 👍

**Comment by 0kolya0** [comment]
@mob41 bad english XD

**Comment by a1aw** [comment]
> > > Hi, make a download error in the browser when the download fails
> > 
> > 
> > @0kolya0 Sorry... what do you mean? 😕
> 
> if osumer download error auto open beatmaps on browsers

Yeah that would be good. Let see if I can add this in further releases.

**Comment by Adim2P** [comment]
Well, the program doesn't work for me? It just redirects all of my beatmap
links to the actual browser itself instead of the program downloading the
beatmap, i know this is a WiP and is currently in beta but this is a neat
program and idea, i'm not complaining about the current errors I have since
I can still use the beatmap search feature on the program, keep up the good
work tho, I'll see what I can do from here to make this program run

**Comment by a1aw** [comment]
Have you finished the last step of the installation? You have to set osumerExpress as default browser before you can use it.
https://github.com/mob41/osumer#installation-of-osumerexpress

**Comment by a1aw** [comment]
![Capture](https://user-images.githubusercontent.com/12967084/56818176-a4febc00-6879-11e9-924a-8274a02e1e0d.PNG)

**Comment by Adim2P** [comment]
Yup doesn't work I set the program 3 times and even restarted my computer
nothing happened.

**Comment by 0kolya0** [comment]
@mob41 
![image](https://user-images.githubusercontent.com/36767025/56818294-027e1300-6850-11e9-90a5-4ca4b6a5fcb9.png)

**Comment by a1aw** [comment]
Go to osumer2's ```Preferences``` and check is ```Disable osumerExpress``` is not checked.

Can you try doing this?

1. ```Windows Key + R``` and a window jumps up
2. Type ```"C:\Program Files\osumer\osumer.exe" https://osu.ppy.sh/s/320118```
3. Press Enter

- If it starts downloading with a sound, it should be working. And then the default browser should be the problem.
- If it redirects to the actual browser, there should be some problems in your configuration.
- If nothing happens, hmm... let me know.

**Comment by a1aw** [comment]
@0kolya0 The whole queue UI is changed in the next release. And it should include what you just suggested. I am doing something huge in the applcation's source code these days.

**Comment by 0kolya0** [comment]
@mob41 hmm Nice!

**Comment by a1aw** [comment]
I am sorry about that I do not have any documentation and tutorials since osumer's version 2. All tutorials and YouTube video is for version 1. I will make if I really have time. So sorry about that.

**Comment by 0kolya0** [comment]
@mob41 create bat file for delete osumer

**Comment by 0kolya0** [comment]
@mob41 
A bat is in the same folder as the files to be deleted. The number of dots is the number of characters in the file. The spaces in the file are counted as characters.

@echo off
Setlocal EnableDelayedExpansion
For  %%a in (*.*) do (
set "A=%%~na"
for /f "delims=" %%b in ('echo !A!^|findstr /v /x /r /c:"....."') do (
del "%%~dpnxa"
)
)
exit /b

**Comment by a1aw** [comment]
@0kolya0 If you want to know:
The right-click function does exist in the current version of the application. It just doesn't work, because of a bug: the queue UI constantly updates, and constantly closes the menu 😭. The next release will be event-oriented and with Java RMI technology. More better memory performance and experience (?)

You will understand even you don't know how to code: https://github.com/mob41/osumer/blob/2.0.0-SNAPSHOT-b5/src/main/java/com/github/mob41/osumer/ui/UIFrame.java#L643

**Comment by a1aw** [comment]
> @mob41
> A bat is in the same folder as the files to be deleted. The number of dots is the number of characters in the file. The spaces in the file are counted as characters.
> 
> @echo off
> Setlocal EnableDelayedExpansion
> For %%a in (_._) do (
> set "A=%%~na"
> for /f "delims=" %%b in ('echo !A!^|findstr /v /x /r /c:"....."') do (
> del "%%~dpnxa"
> )
> )
> exit /b

We need a way to delete all files cleanly. This will left the batch file behind in the program files. The most possible way to use Windows Installer wizards directly.

**Comment by a1aw** [comment]
This is also one of the reason why I require you guys to use a "external" osumer downloaded again from the releases or copied from the program files, in order to uninstall it.

**Comment by 0kolya0** [comment]
> > @mob41
> > A bat is in the same folder as the files to be deleted. The number of dots is the number of characters in the file. The spaces in the file are counted as characters.
> > @echo off
> > Setlocal EnableDelayedExpansion
> > For %%a in (_._) do (
> > set "A=%%~na"
> > for /f "delims=" %%b in ('echo !A!^|findstr /v /x /r /c:"....."') do (
> > del "%%~dpnxa"
> > )
> > )
> > exit /b
> 
> We need a way to delete all files cleanly. This will left the batch file behind in the program files. The most possible way to use Windows Installer wizards directly.
=)
Del batch_file_name.bat

**Comment by a1aw** [comment]
The most important thing is that batch files cannot handle registry stuff dynamically and properly. 😅

**Comment by 0kolya0** [comment]
@mob41 I think for the first time everything should be fine and then it will be possible to improve next time.

**Comment by Adim2P** [comment]
@mob41 Ok I was able to reinstall Opera and reinstall osumerExpress I tried doing the manual queuing, and it started downloading inside the program, now It can't be the def browser with the problem since in game when I click the beatmap it redirects me to the actual browser, it doesn't download in the program, is this a bug or am I doing something wrong?

**Comment by a1aw** [comment]
> Go to osumer2's `Preferences` and check is `Disable osumerExpress` is not checked.
> 
> Can you try doing this?
> 
> 1. `Windows Key + R` and a window jumps up
> 2. Type `"C:\Program Files\osumer\osumer.exe" https://osu.ppy.sh/s/320118`
> 3. Press Enter
> 
> * If it starts downloading with a sound, it should be working. And then the default browser should be the problem.
> * If it redirects to the actual browser, there should be some problems in your configuration.
> * If nothing happens, hmm... let me know.

@Adim2P Have you tried this already? Please tell me the results, otherwise I could not find the problem of your issue!!! 😕

**Comment by Adim2P** [comment]
Yes I tried all of that, I launched osumer via the win + r I inputed the
beatmaplink, the queueing works it downloads the beatmap and imports it in
osu!, the disable osumerExpress is not ticked, but in game the when I click
download, it just opens my browser to the beatmap link.

**Comment by a1aw** [comment]
@Adim2P Then the problem should be the default browser thing, not about osumer, because you are able to do the above stuff. It is known that Windows have problems with handling default browsers.

https://superuser.com/questions/950434/windows-10-wont-accept-firefox-as-the-default-browser

It is so annoying. Try this solution:

<b>Solution 1</b>
1. Navigate to ```Settings -> Apps -> Default apps```
2. Set ```Web browser``` as ```osu! express beatmap downloader```
3. Try to download beatmap in osu!

<b>Solution 2</b>
1. Navigate to ```Settings -> Apps -> Default apps```
2. Scroll to the near bottom
3. Click ```Set defaults by app```
4. Find ```osumerExpress```, click into it and click ```Manage```
2. Set ```HTTP``` as ```osu! express beatmap downloader```
2. Set ```HTTPS``` as ```osu! express beatmap downloader```
3. Try to download beatmap in osu!

Please tell me if solution 1 or 2 works.

**Comment by Adim2P** [comment]
Omfg, solution 2 worked, thanks man the osumer works fine it downloads
beatmap and imports it thanks man for such a neat program.

**Comment by a1aw** [comment]
It is good to see that. As a result, I will mark solution 2 as the way to set default browser in the future then.
