### ISSUE TITLE
Windows 7 stopped at 100%, no osumer beatmap import, when used actual browser to download

### ISSUE THREAD

**Issue by Adim2P** [mob41/osumer#23]
I encountered something in 2.0.0 snapshot 5, osu!mer works fine after beatmaps download directly from the game, but once you downloaded a beatmap from a browser itself, the program would not import any beatmap to osu, it'll queue and download the beatmap but it won't import it, is this a bug or something I tick off in the options or preferences, and as much as I hate to admit the program doesn't popup a beatmap information screen on osu whenever you download a beatmap it just automatically imports it and download it without showing any information. Oh and about the bug to fix it I have to restart my computer without downloading any beatmaps on the actual browser everything must be downloaded from osu!mer if I want to download on it.

**Comment by a1aw** [comment]
You might have changed the "Default After-Download Action and Location" settings in the preferences. 

1. Navigate from the toolbar ```osumer2 > Preferences```.
2. Click the ```Downloading``` tab. Change to ```Launch osu! automatically to import beatmap (Default & Recommended)```, and click ```Save```.

**Comment by Adim2P** [comment]
> You might have changed the "Default After-Download Action and Location" settings in the preferences.
> 
> 1. Navigate from the toolbar `osumer2 > Preferences`.
> 2. Click the `Downloading` tab. Change to `Launch osu! automatically to import beatmap (Default & Recommended)`, and click `Save`.

Nope literally didn't change anything from the preferences menu, it's really like that once I download a beatmap from an actual browser it'll stop importing beatmaps when I download in osumer

**Comment by a1aw** [comment]
> I hate to admit the program doesn't popup a beatmap information screen on osu whenever you download a beatmap it just automatically imports it and download it without showing any information.

I have started implementing osumer overlay in osu! using C++ dll injection. It is in near future 😄 

>it's really like that once I download a beatmap from an actual browser it'll stop importing beatmaps when I download in osumer

I have tested it just now with the latest version. I haven't experienced this problem. How often you experience this problem? Can you explain how can you reproduce this problem.

**Comment by Adim2P** [comment]
> > I hate to admit the program doesn't popup a beatmap information screen on osu whenever you download a beatmap it just automatically imports it and download it without showing any information.
> 
> I have started implementing osumer overlay in osu! using C++ dll injection. It is in near future 
> 
> > it's really like that once I download a beatmap from an actual browser it'll stop importing beatmaps when I download in osumer
> 
> I have tested it just now with the latest version. I haven't experienced this problem. How often you experience this problem? Can you explain how can you reproduce this problem.

wait you're gonna use c++ dll injections? Wouldn't that trigger the game's handle detectors? I mean its not opening any handles and modifying them, but it's certain that its modifying something it's injecting a dll.


I'm not exactly sure how to reproduce this problem, but I'm in Windows 7 so I think it's an OS exclusive problem. (I would move to Win10 soon just enjoying the 7's company till it ends in 2020) But it's exactly that download a beatmap on an actual browser that osu!mer is assigned in and try to exit the browser then play a multiplayer game then download a beatmap then osu!mer would download the beatmap but won't import it.

**Comment by a1aw** [comment]
>wait you're gonna use c++ dll injections? Wouldn't that trigger the game's handle detectors? I mean its not opening any handles and modifying them, but it's certain that its modifying something it's injecting a dll.

No, DLL Injection is legal if I did not touch anything that is illegal to touch. All overlays including Steam, NIVIDA, Origin, video recording softwares, etc. all uses injection to put an overlay. You can kindly search in Google about these. The program just put an overlay showing the osumer download status and buttons. I don't think so that this is counted as cheating.

**Comment by a1aw** [comment]
Instead of really modifying something, the osumer overlay only puts a hook on the OpenGL rendering part and draws something on top of osu! full-screen. It is impossible to draw anything on top of osu! without hooking into OpenGL layer, unless you are running in borderless fullscreen mode, which greatly increases your input latency.

**Comment by a1aw** [comment]
>I'm not exactly sure how to reproduce this problem, but I'm in Windows 7 so I think it's an OS exclusive problem. (I would move to Win10 soon just enjoying the 7's company till it ends in 2020) But it's exactly that download a beatmap on an actual browser that osu!mer is assigned in and try to exit the browser then play a multiplayer game then download a beatmap then osu!mer would download the beatmap but won't import it.

Does the beatmap you tried to download contains ```* ?``` etc. illegal characters? This is a known issue in osumer that it would start downloading but does not save the file with an error. #21

**Comment by a1aw** [comment]
Does any errors occurred when it is trying to import? You can check them in ```osumer2 > View Dumps```

**Comment by Adim2P** [comment]
> > wait you're gonna use c++ dll injections? Wouldn't that trigger the game's handle detectors? I mean its not opening any handles and modifying them, but it's certain that its modifying something it's injecting a dll.
> 
> No, DLL Injection is legal if I did not touch anything that is illegal to touch. All overlays including Steam, NIVIDA, Origin, video recording softwares, etc. all uses injection to put an overlay. You can kindly search in Google about these. The program just put an overlay showing the osumer download status and buttons. I don't think so that this is counted as cheating.


> Instead of really modifying something, the osumer overlay only puts a hook on the OpenGL rendering part and draws something on top of osu! full-screen. It is impossible to draw anything on top of osu! without hooking into OpenGL layer, unless you are running in borderless fullscreen mode, which greatly increases your input latency.

Oh I'm a current average in C++ programming, I made a similar program for CSGO that is a bot that calculates other player's behaviour (aiming , visuals) and if the bot founds erratic and suspicious offsets the player produce (aim lock or aim bot , force aim) my program would auto report the player, but to be able to read the offsets the player produce I needed to like inject a dll which READS but doesn't modify anything, anddddd TL;DR my csgo acc got banned in the process just a short story lmfao.




> Does any errors occurred when it is trying to import? You can check them in `osumer2 > View Dumps`

That's what I'm trying to do I wanted to find an error pop up so I can send the dump file but it doesn't give any error it downloads the beatmap stuck in 100% but doesn't import it.

**Comment by a1aw** [comment]
>calculates other player's behaviour (aiming , visuals) and if the bot founds erratic and suspicious offsets the player produce (aim lock or aim bot , force aim) my program would auto report the player, but to be able to read the offsets the player produce

With the fact that you can automatically report that player and the ability to calculate offsets of the player, you are probably touching the stuff that is not suitable to touch. An overlay would be not that bad if I am not touching the API methods and variables from the osu! application.

>That's what I'm trying to do I wanted to find an error pop up so I can send the dump file but it doesn't give any error it downloads the beatmap stuck in 100% but doesn't import it.

I am sorry to hear that. Then there might be a problem with Windows 7 O/S. Let this issue stay open to see what I can do for it later.

**Comment by Adim2P** [comment]
Don't make this a big issue for your program since Windows 7 is a dying os
anyways just focus on adding the overlay and it'll be fine, I'll see what I
can do here to make this bug go away I have little to no knowledge on Java
Coding at all lmao but keep me updated if you found anything interesting to
drift to.
