### ISSUE TITLE
Status: Error occurred while downloading

### ISSUE THREAD

**Issue by Adim2P** [mob41/osumer#24]
So new error? No dumps no everything, this started happening yesterday, osu!mer would just get the beatmap link then start the queue then say this error everytime I download something I did check the default browsers all the same nothing was changed, I did even reinstall osu!mer no avail still didn't work it would queue but would not start the download, any reasons why, or the program become broken?

**Comment by a1aw** [comment]
This is fixed in build 6 and going to be released soon. Please disable it for a while.

**Comment by a1aw** [comment]
Update your osumer to Build 6 to fix it. Remember to enable back the osumerExpress option
