### ISSUE TITLE
3 Bugs down, a lot more popped up.

### ISSUE THREAD

**Issue by Adim2P** [mob41/osumer#25]
So, B6 was good the UI overhaul was good, heres the problems, overlay on osu! doesn't work atleast for me or any Windows 7 users, it always says this error after clicking 'run osu with overlay' on preferences "Error Could not call daemon to start osu!: Error occured in server thread; nested exception is: java.lang.NoClassDefFoundError: Could not initialize class com.github.mob41.osumer.OsumerNative" I don't know if it's an OS Exclusive error but it happens to me the queing was fine the beatmaps downloads and the program import the song no problem, but upon using the new setup for B6, I ran into a couple of problems for starting it, using the shortcut that is created on desktop opening it will open a process at precisely 75 mb of memory and get killed, I'm using a Process Hacker 2 program to know how process we're ended and it was forcibly shutted down, so what I did is traced the root directory of the program, now there we're 2 .exe? Daemon and the UI execution files? Opening the Daemon starts the process but it doesn't opening anything else I can download beatmaps and import it, so I was wondering where is the preferences windows pop up? So the UI execution was there, I opened it and it opened a new windows pop up with the overhauled GUI everything works fine, but the Overlay and the Program Opening doesn't work (the shortcut that is opened in the dektop it just opens a 'jawaw' process and dies idfk why) tho good job on the UI overhaul, If I only knew how to Java Script I can maybe collaborate and help you lmao. Oh and the memory usage overhaul is amazing as well from 270 mb usage to 120 mb usage great job dude.

**Comment by a1aw** [comment]
About the root directory of the application, there are 3 exe files currently.

osumer-daemon starts the daemon in the background and will not show anything.

osumer-ui starts the user interface to communicate with the daemon.

But please do not manually start them. There’s a file osumer.exe that automatically handles these things for you. It automatically starts the daemon if not started and starts the UI afterwards. It may takes time to execute.

**Comment by a1aw** [comment]
>Error occured in server thread; nested exception is: java.lang.NoClassDefFoundError: Could not initialize class com.github.mob41.osumer.OsumerNative

I haven’t experienced this problem before. Have you installed B6 properly? Uninstall it via the control panel and install it again.

**Comment by a1aw** [comment]
The Preferences is located at the menubar of the UI “File > Preferences”

**Comment by Adim2P** [comment]
Well I did wait for the .exe to pop up but once the original osumer.exe was
opened it will open a process then will get shut down, so the onlt way for
me to use the UI is to open manually the ui execution, I did properly
install B6 as well using the setup.exe and the osumer.msi for repairing
still didn't do anything.

**Comment by mob41** [comment]
Please help me to check something.

1. Terminate all Java applications / osumer2 applications.
2. Press ```Windows Key + R```. And type ```cmd```
3. Type ```cd "%ProgramFiles(x86)%\osumer2"```
4. ```jre\bin\java.exe -jar osumer-daemon.exe```
5. Start ```osumer-ui.exe``` in the folder

Check any outputs starting with ```Exception```

**Comment by mob41** [comment]
And I am starting a VM to see if it is a OS exclusive problem to Windows 7.

**Comment by mob41** [comment]
It is a compiler problem. It is fixed and repackaged in the releases. Please download it and try it again.

**Comment by a1aw** [comment]
I have updated the releases.

1. Install ```vc10redist_x86.exe``` and ```vc15redist_x86.exe``` from the releases first.
2. Download the ```Release.zip``` again. Uninstall the current one first, and install with the latest ```setup.exe```.

**Comment by a1aw** [comment]
See if the problem still exists. The problem is about my compiler and Windows 7 does not have some redistributables pre-installed.

**Comment by Adim2P** [comment]
Ok I'll do what you asked first on the troubleshooting before I install the
new packages so you can get an overview on whats going on, and yeah using a
VM can be good as well.

**Comment by Adim2P** [comment]
I'll updated you within 2 hours.

**Comment by a1aw** [comment]
> I have updated the releases.
> 
> 1. Install `vc10redist_x86.exe` and `vc15redist_x86.exe` from the releases first.
> 2. Download the `Release.zip` again. Uninstall the current one first, and install with the latest `setup.exe`.

I have found out the problem. You can just install the latest uploaded installer and redistributables.

**Comment by a1aw** [comment]
Did you experience ```The program cannot start because XINPUT1_4.dll is missing from your computer.``` ?

**Comment by a1aw** [comment]
This is due to problem that https://docs.microsoft.com/en-us/windows/desktop/xinput/xinput-versions XInput1.4 is only available on Windows 8 or newer OS. I am sorry to say that Windows 7 might not support osumer2 Overlay currently.

**Comment by Adim2P** [comment]
I haven't tested the overlay yet let me try I'll give you  a feedback after
I tested it, so far I didn't even get any .dll errors

**Comment by Adim2P** [comment]
I have some tricks up my sleeve I encountered xinput1_4.dll error before in
UE4 engine coders, the only way to fix it was to hardcode it into a library
file, but it will only work for one program but you were using a java
program, so its out of my league i just encoded into the windows library
files and it worked.

**Comment by a1aw** [comment]
I have forced it to use older version of XInput (1.3) and fixed some errors. I did not release a new version for it, just download the latest Release.zip from the releases. Uninstall the existing one first, and install the new one.

**Comment by a1aw** [comment]
It should work on Windows 7 now.

**Comment by Adim2P** [comment]
Thanks dude kay amma download the latest release osu keeps crashing when i
hardcoded xinput1_4

**Comment by a1aw** [comment]
Please do not do anything unnecessary. I do not know what you mean for hardcoding, and hardcoding does not mean like that.

I have fixed the problem and just reinstall the program with the installer in the release.
