### ISSUE TITLE
Doesn't work after Osu 20190524 stable update?

### ISSUE THREAD

**Issue by Adim2P** [mob41/osumer#26]
Would click on the link, but doesn't put the downloading in queue opened process hacker again just some jawaw.exe opening and closing, I tried repairing osumer didn't work full pc restart still didn't work, did you notice it as well? I even tried uninstalling express and installing again still didn't alleviate the problem.

**Comment by a1aw** [comment]
Notified. Investigating into the issue right now.

**Comment by a1aw** [comment]
The problem noticed is that osu! changed its way in displaying its beatmap on its webpage. The parser has to be changed.

**Comment by Adim2P** [comment]
So, you're gonna release a new build, or just gonna fix the current build?

**Comment by a1aw** [comment]
probably release a new build

**Comment by a1aw** [comment]
Fixed in B7
https://github.com/mob41/osumer/releases/2.0.0-SNAPSHOT-b7
