### ISSUE TITLE
new version doesnt work...

### ISSUE THREAD

**Issue by SilverRatchet** [mob41/osumer#27]
it just doesnt work… each time i launch osumer 2 i get either a "unable to connect to daemon. Terminating" or "unable to connect to UI. Terminating" it doesnt crash but i cant really do anything about it. i can acess the UI and the settings but after trying pretty much everything i could think i didnt change anything. i tried to do the solution from another thread but solution 1 didnt work and for solution 2 i can find osumer!express anywhere when i searche it to put it as default web browser.

**Comment by a1aw** [comment]
Is your computer quite slow or laggy something?

**Comment by a1aw** [comment]
>but after trying pretty much everything i could think i didnt change anything

What did u mean you cannot change anything?

**Comment by 0kolya0** [comment]
@mob41 
After restarting, the osumer does not work.
You need to close the program and open it yourself. (Windows 10;gtx 1070;amd ryzen 5)

**Comment by a1aw** [comment]
@0kolya0 This problem should be fixed in B7. Try it out.

**Comment by 0kolya0** [comment]
@mob41 make the overlay work only when the map is loaded. =)

**Comment by a1aw** [comment]
>make the overlay work only when the map is loaded. =)

I don't get what you mean 😕

**Comment by 0kolya0** [comment]
@mob41 When you open osu, overlay shouldn’t work all the time, but only when you load song

**Comment by a1aw** [comment]
You mean close the "osumer2" window in osu! when not using it?

**Comment by 0kolya0** [comment]
@mob41 yes only works when you use

**Comment by a1aw** [comment]
Okay, let me take a note for this.

**Comment by 0kolya0** [comment]
@mob41 end remove this 
![image](https://user-images.githubusercontent.com/36767025/58367170-b53fa080-7ee4-11e9-971d-0c0739d6cb78.png)

**Comment by a1aw** [comment]
Yea, I will let it to remember your choice of agreement later

**Comment by 0kolya0** [comment]
@mob41 Thanks

**Comment by a1aw** [comment]
@0kolya0 You should open a new issue for your questions and problems instead. Don't comment on others' issue for another problem.

**Comment by 0kolya0** [comment]
@mob41 XD sorry

**Comment by SilverRatchet** [comment]
> but after trying pretty much everything i could think i didnt change anything
> 
> What did u mean you cannot change anything?

by that i mean that the same error appears… i can't even dowload through the search bar in the UI

**Comment by SilverRatchet** [comment]
> Is your computer quite slow or laggy something?

yes i have a pretty shitty pc. that why i use osumer… i cant run osu and my browser at the same time otherwise either osu or my browser crashes or have very little fps to play with

**Comment by a1aw** [comment]
Navigate from the menubar ```File > Debug > View Dumps```. Drag all the dump files to here. If there are so many dumps files, drag the latest 6 ones.

**Comment by SilverRatchet** [comment]
Guess it works now. I reset my pc and it works. I'm just a little sad that this version is slower than the previous one

**Comment by a1aw** [comment]
Starting up the UI might take time because it has to connect to the daemon for communication.

The slowness might also due to the change of UI because the new UI used JavaFX, which is a bit heavier than the one used before (Java Swing). But in exchange...... an awesome UI design...

**Comment by a1aw** [comment]
>Guess it works now. I reset my pc and it works. I'm just a little sad that this version is slower than the previous one

I would like to have those dump files for further investigation on your issue. P.S. Those files won’t include any of your private information.

These files are meant for debugging purpose.

**Comment by SilverRatchet** [comment]
> > Guess it works now. I reset my pc and it works. I'm just a little sad that this version is slower than the previous one
> 
> I would like to have those dump files for further investigation on your issue. P.S. Those files won’t include any of your private information.
> 
> These files are meant for debugging purpose.

i would like too but i reseted my pc... meaning i dont have any data left. I had more than one reasons to reset it but i guess osumer not working is what made me reset it 🤷‍♂

**Comment by a1aw** [comment]
I am sorry to hear that. I will close the issue now as the problem has been resolved.
