### ISSUE TITLE
There is no Opera or Opera GX in osumer app

### ISSUE THREAD

**Issue by NatsukashiiOwU** [mob41/osumer#29]
### My environment

- My operating system: *Windows 10 1803*

- My Java Version: *Java 8 update 181*

### About my issue

Hello everyone, i had an issue about my default web browser. It hasn't been showing in osumer. So i spend some time editing my registry and now i am writing this for people who has such problem.

First of all you need to check out if your browser isn't showing in osumer app and showing in windows default apps. 
![Screenshot_41](https://user-images.githubusercontent.com/38032753/60767566-d6da9d00-a0ca-11e9-8a1f-32d0158de67a.png)
![Screenshot_43](https://user-images.githubusercontent.com/38032753/60767567-d7733380-a0ca-11e9-8630-710dea7b7a70.png)

If it is you must edit your registry.
The easyest way to do this is creating a file named *type any name here*.reg and importing some code below to it, then edit the last string for your browser install path, then just save and open it with admin rights (all the configs was made for opera gx so you can edit it as you want).
![Screenshot_44](https://user-images.githubusercontent.com/38032753/60767584-0c7f8600-a0cb-11e9-90f8-b03e330c8d72.png)

If you done this right you would see Opera GX in browser to forward to in osumer, choose it and try to open some links.
![Screenshot_45](https://user-images.githubusercontent.com/38032753/60767594-2de07200-a0cb-11e9-90e9-33adc29b592a.png)

> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX]
> @="GX"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\Capabilities]
> "ApplicationName"="GX"
> "ApplicationDescription"="GX"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\Capabilities\Startmenu]
> "StartMenuInternet"="GX"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\Capabilities\URLAssociations]
> "http"="GX"
> "https"="GX"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\DefaultIcon]
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\InstallInfo]
> "IconsVisible"=dword:00000001
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\shell]
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\shell\open]
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Opera GX\shell\open\command]
> @="G:\\GX\\Launcher.exe\\"

Hope it will help someone as it helped me.

**Comment by a1aw** [comment]
This is another good solution to deal with browsers that are not properly registered in the Windows Registry. I will soon add an option to support unsupported/custom browsers.
