### ISSUE TITLE
multiplayer download not working

### ISSUE THREAD

**Issue by khylegain** [mob41/osumer#30]
### My environment

- My operating system: *Windows 7*

- My Java Version: Version 8 Update 221

### About my issue
So like the manual download is working but when I join a multiplayer server the ingame (osu direct-like) downloader isn't working. All it does is direct me to a website then ye manual download in there

**Comment by a1aw** [comment]
You might have missed step 3. You have to set the system default browser as "osumer2" to work. Otherwise, the features would not work.

https://github.com/mob41/osumer#installation-instructions

**Comment by khylegain** [comment]
> You might have missed step 3. You have to set the system default browser as "osumer2" to work. Otherwise, the features would not work.
> 
> https://github.com/mob41/osumer#installation-instructions

Hi I just did it and its the same. its still directing me to the beatmap link. In my osumer settings I have  'Browser forwarded to: Google Chrome'. I tried osumer2 but its the same. I have the osumer overlay on osu already but it still doesnt have the direct download like osu direct

**Comment by khylegain** [comment]
Hi I just noticed. When I do the step 3 and select osumer2. After closing the control panel and going to the default program thingy the selection is selecting 'use default browser' automatically once i close it

**Comment by a1aw** [comment]
Take a look of this: https://github.com/mob41/osumer/issues/22#issuecomment-487303717 . It might be a problem of Windows.

**Comment by khylegain** [comment]
errr I used windows 7 xd

**Comment by khylegain** [comment]
ughhh it just wont workkk

**Comment by a1aw** [comment]
Have you pressed OK to submit the changes in the Default Programs dialog?

**Comment by a1aw** [comment]
Is this problem solved? I am going to close this issue soon.
