### ISSUE TITLE
Does it still works?

### ISSUE THREAD

**Issue by shoxers** [mob41/osumer#33]
Does osumer still works? i seems cant make it to work

**Comment by a1aw** [comment]
Please view #32

**Comment by Jirubizu** [comment]
@shoxers Got it working with new settings, Will happily upload the files :)

**Comment by shoxers** [comment]
> @shoxers Got it working with new settings, Will happily upload the files :)

would really be happy to use it <3 <3 <3

**Comment by Jirubizu** [comment]
@shoxers view [#32 ](https://github.com/mob41/osumer/issues/32) I posted the file and what to replace
