### ISSUE TITLE
Browser Forwarding Suggestion

### ISSUE THREAD

**Issue by AwesomeFTW** [mob41/osumer#36]
Windows 10 

Java version (build 1.8.0_251-b08)

In the settings the browser forwarding function doesn't seem to acknowledge that I have Opera or Opera GX installed. This would be a pretty useful inclusion, at least for me and future users that happen to use these browsers. It said to select all and delete for a feature suggestion so I _think_  this isn't misuse?
There seems to be an issue with browsers detection in general, you just add all them by hand right? Seems tough. Don't know much coding, would have helped otherwise.
![image](https://user-images.githubusercontent.com/64756813/92160530-d60cda80-ee37-11ea-84d9-b801cb3b1d9d.png)

**Comment by a1aw** [comment]
> doesn't seem to acknowledge that I have Opera or Opera GX installed.

It is surprisingly Opera and Opera GX does not register themselves in the ```Start Menu\Internet``` registry like common browsers would do. See #29 and people made a quick solution. I will add a way to select custom browser in the future. 

> There seems to be an issue with browsers detection in general, you just add all them by hand right? Seems tough. Don't know much coding, would have helped otherwise.

No, osumer reads the currently installed browsers from the registry directly, which I expect most browsers that register themselves correctly could be shown there.

https://github.com/mob41/osumer/blob/master/osumer-installer/src/main/java/com/github/mob41/osumer/installer/Installer.java#L216

**Comment by AwesomeFTW** [comment]
Oh right... sorry for the bother then. I'll do that manually. Sweet app, thanks.
