### ISSUE TITLE
why i can't download beatmap

### ISSUE THREAD

**Issue by mantapbagoes** [mob41/osumer#38]
![seveeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee](https://user-images.githubusercontent.com/75229889/100560242-d0644b00-32e7-11eb-942f-0151ecf57039.png) why ican't download with this _issue_

**Comment by a1aw** [comment]
I don't have the similar issue in my client. Your issue is related to #35 which is unfixable. If I have time I will try investigating the new API to see if it can fix that. Please keep track on that issue then.
