### ISSUE TITLE
osumer updater down't work

### ISSUE THREAD

**Issue by poprox24** [mob41/osumer#39]
### My environment
- My operating system: Windows 10 64bit

- My Java Version: jre1.8.0_271, jdk.1.8.0_271, jdk-11.0.9(In java_home), jdk-14.0.2(In java_home)

### About my issue
osumer check for updates/updater doesn't work, it says:

osumer-updater:
could not get upload info

osumer check for updates:
Error Checking Update - Could not obtain update info.

### Dump files
[Dump Files.zip](https://github.com/mob41/osumer/files/5684453/Dump.Files.zip)

**Comment by a1aw** [comment]
Your DNS server does not resolve the Github Pages domain ```mob41.github.io```. Try changing your DNS servers to ```8.8.8.8``` or ```8.8.4.4``` (Google public DNS), clean DNS cache and try again.

```
Data specified: https://mob41.github.io/osumer-updater/versions.json

Exception stacktrace: 
com.github.mob41.osumer.debug.WithDumpException: java.net.UnknownHostException: mob41.github.io
	at com.github.mob41.osumer.updater.Updater.getVersions(Updater.java:140)
	at com.github.mob41.osumer.updater.Updater.getLatestVersion(Updater.java:176)
	at com.github.mob41.osumer.ui.MainController.getUpdateInfoByConfig(MainController.java:735)
	at com.github.mob41.osumer.ui.MainController.access$21(MainController.java:730)
	at com.github.mob41.osumer.ui.MainController$17.run(MainController.java:830)
Caused by: java.net.UnknownHostException: mob41.github.io
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
```

**Comment by a1aw** [comment]
1. change dns servers (https://developers.google.com/speed/public-dns/docs/using)

2. clean dns cache (https://www.a2hosting.com/kb/getting-started-guide/internet-and-networking/clearing-the-dns-cache-on-your-computer)

**Comment by poprox24** [comment]
Thanks for fast answer, I tried changing the dns, I can open the site "https://mob41.github.io/osumer-updater/versions.json" in browser, but osumer just can't open it.

**Comment by a1aw** [comment]
Then Windows might have blocked the built-in Java from accessing the Internet. Try specifically allowing ```C:\Program Files (x86)\osumer2\jre\bin\javaw.exe``` to pass through the firewall in Public and Private networks.

Do you have another anti-virus/firewall installed in your computer? You also have to allow the above Javaw.exe to access the Internet in those anti-virus/firewall.

![Capture](https://user-images.githubusercontent.com/12967084/102009382-07b80a80-3d72-11eb-8621-57e958619b36.PNG)

**Comment by poprox24** [comment]
It works now, thanks.

**Comment by a1aw** [comment]
It's good to hear that. 😄
