### ISSUE TITLE
Can't set up osumer as default browser in windows settings.

### ISSUE THREAD

**Issue by laurens-vrh** [mob41/osumer#41]
### My environment

- My operating system: Windows 10

- My Java Version: Version 8 Update 281

### About my issue
I can't select osumer as my default browser in windows settings.

![image](https://user-images.githubusercontent.com/66695935/107276520-6ee0fb00-6a53-11eb-9995-e53113ea2706.png)

**Comment by a1aw** [comment]
Sorry for late reply. Try reinstalling osumer to see if it can help.
