### ISSUE TITLE
osumer not working

### ISSUE THREAD

**Issue by xzFakezx** [mob41/osumer#42]
### My environment

- My operating system: *Windows 10 home*

- My Java Version: *idk*

### About my issue When i click on an osu map to download it says could not add or connect queue to daemon for details check dump: java.rmi.UnmarshalException: error unmarshalling return; nested exception is: java.io.WriteAbortedException: writing aborted; java.ioNotSerializableException: com.github.mob41.osumer.debug.DebugDump
 -->

**Comment by a1aw** [comment]
Please submit debug dump files as instructed. File->Debug->View Dumps

**Comment by a1aw** [comment]
Closing this issue as there are no replies yet.
