### ISSUE TITLE
Osumer2 doesn't automatically downloads beatmaps with new URL 

### ISSUE THREAD

**Issue by niel228** [mob41/osumer#44]
- My operating system: *Windows 10 20H2*

- My Java Version: *Java version 1.8.0*

Osumer2 doesn't automatically downloads beatmaps because peppy changed the beatmap url osumer2 only detects beatmaps in the format like this https://osu.ppy.sh/s/1279298#osu/2657559 and not like this https://osu.ppy.sh/beatmapsets/1279298#osu/2657559 if the link contains "beatmapsets" instead of "S" or "B" osumer2 doesn't work

**Comment by a1aw** [comment]
It has been noticed in #43 . But I am not currently in a priority and having a time to deal with the problem.

**Comment by niel228** [comment]
kinda sad osumer is such a good tool thanks for the answer have a nice day!

**Comment by a1aw** [comment]
Yes, originally I made this tool when I was young (like 2016) and actively playing osu!, TBH it is really good minimal tool for osu!. But for now, as things getting busier and busier, the development of this tool is getting slower and not put in main priority of mine.

**Comment by niel228** [comment]
I get it. not having a browser eating resources when playing osu is so good lol thanks for the explanation, i'm glad its still in development even after so many years. thanks for the explanation.

**Comment by Suthanai20682** [comment]
> * My operating system: _Windows 10 20H2_
> 
> * My Java Version: _Java version 1.8.0_
> 
> Osumer2 doesn't automatically downloads beatmaps because peppy changed the beatmap url osumer2 only detects beatmaps in the format like this https://osu.ppy.sh/s/1279298#osu/2657559 and not like this https://osu.ppy.sh/beatmapsets/1279298#osu/2657559 if the link contains "beatmapsets" instead of "S" or "B" osumer2 doesn't work

Actually it's "beatmaps" https://osu.ppy.sh/beatmaps/(beatmap id) but the link redirect/change very fast to beatmapsets.
