### ISSUE TITLE
Error when trying to start the software

### ISSUE THREAD

**Issue by sirzento** [mob41/osumer#49]
An friend of mine tryes to start osumer2 but gets this error message: https://i.imgur.com/remHnHe.png

It was installed via the updater and java + the two requirements are installed. Any Idea for that?

**Comment by a1aw** [comment]
Are the [vc10redist_x86.exe](https://github.com/mob41/osumer/releases/download/2.0.0-SNAPSHOT-b11/vc10redist_x86.exe) and [vc15redist_x86.exe](https://github.com/mob41/osumer/releases/download/2.0.0-SNAPSHOT-b11/vc15redist_x86.exe) installed?

**Comment by sirzento** [comment]
I think so,yes.

This is what is shown if vc15 is runned: https://i.imgur.com/T5UkLDP.png
Means in english that there is an setup error because a differend version of this product is already installled.
English screenshot from internet: https://i.imgur.com/0EFC1KO.png

And for vc10: https://i.imgur.com/9owibd9.png
Means in english that this software is already installed and here you can chose to repaire/reset it or uninstall it

**Comment by sirzento** [comment]
So he uninstalled two 2017 version of c++ and then he could install the 2015 version but the software still doesnt start. Even after a reinstall.

Here are both screenshot of the c++ software from the program and app section under windows:

https://i.imgur.com/4d6aD2D.png
https://i.imgur.com/0yJAe9z.png

**Comment by a1aw** [comment]
Are your friend using Windows 11?

**Comment by sirzento** [comment]
No, windows 10 21H2

**Comment by a1aw** [comment]
i tested working on 21H1 only, probably due to changes of the VC++ 2010, 2015 runtimes that I cannot catch up anymore. For the time being I cannot fix it.
