### ISSUE TITLE
Indexing traffic request

### ISSUE THREAD

**Issue by mob41** [mob41/osumer#7]
Dear @peppy,

As long as the program grows, I am adding beatmap searching functions that will do indexing from the official osu! page. Where the program will fetch all the pages (~400-unlimited beatmaps) from the osu! server.

As I am afraid about this will increase osu! server traffic, I am wondering that am I allowed to do this?

Best regards,
mob41

**Comment by peppy** [comment]
please don't

**Comment by mob41** [comment]
Actually it is meaningless though😅 The beatmap list on the web is not showing all the beatmaps😂 Sorry.

**Comment by mob41** [comment]
I think I would rather do search caching instead.
