### ISSUE TITLE
Search Beatmaps [use online web search]

### ISSUE THREAD

**Issue by Stonaaz** [mob41/osumer#8]
how do I use the online web search search in Search Beatmaps, I search and it appears "you must be logged into osu! forum to perform online search." I'm already logged in to the program. sorry my English is bad

**Comment by a1aw** [comment]
This is a bug. I will be fixing in build 3

**Comment by a1aw** [comment]
Searching works  in build 1 but broke in build 2😗🙃

**Comment by a1aw** [comment]
Solved. You may download at https://github.com/mob41/osumer/releases/tag/2.0.0-SNAPSHOT-b3 manually or wait for the update to arrive to your program. (The “Update available” dialog)

**Comment by Stonaaz** [comment]
Thank you, you are a great programmer. =D
