### ISSUE TITLE
Mode to finish queue one by one

### ISSUE THREAD

**Issue by takase1121** [mob41/osumer#9]
Hi mob41, I used osumer2_SNAPSHOT_B3 for a while now. It was great. The Express works just fine and I can now download beatmaps easily. 
However, my Internet speed was very slow. In fact, its usually on 8kBytes\second with several timeouts along the way. osumer handles the timeout flawlessly, but the problem is that when I download multiple beatmaps at once, all download starts almost at the same time. For my slow internet connection, it surely takes time. Not only that, but if I am not wrong, osu! beatmap links will timeout after a certain time. So, I hope that there is a mode that will let osumer to finish the queue one by one. Please tell me if I missed something and sorry if I had any mistakes here. Thank you.

**Comment by a1aw** [comment]
You can set can set maximum running queue in preferences.

Go to ```Preferences``` > ```Queuing``` and set ```Maximum Downloading Thread``` as 1.
Then you can finish queue one by one 😄

**Comment by takase1121** [comment]
Thank you!
